apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
  labels:
    app: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts-jdk11
        securityContext:
          privileged: true
          runAsUser: 0
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: jenkins-home
            mountPath: /var/jenkins_home
          - name: dockersock
            mountPath: "/var/run/docker.sock"
            readOnly: false
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: pvc
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
          type: File
---
