apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: jenkins
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
